development:
  secret_key_base: ca0017f01022f78f5eaa193bb79c773ea47ef506935da12b8bf2ec4329f0a1d1219c8c650c91715c95d912deede5b9df66a0b088954a5ce763a9a64b656af1eb
  twitch_bot_user: <%= ENV['twitch_bot_user'] %>
  twitch_bot_pass: <%= ENV['twitch_bot_pass'] %>
  server_home: <%= ENV['server_home'] %>

production:
  secret_key_base: <%= ENV['secret_key_base'] %>
  twitch_bot_user: <%= ENV['twitch_bot_user'] %>
  twitch_bot_pass: <%= ENV['twitch_bot_pass'] %>
  server_home: <%= ENV['server_home'] %>
